### ISSUE TITLE
panic in RawTask drop_task

### ISSUE THREAD

**Issue by LizardWizzard** [DataDog/glommio#379]
Hello! I'm using glommio to experiment with async rust and especially asynchronous file IO. While trying to implement write ahead log I faced strange panic in drop_task [here](https://github.com/DataDog/glommio/blob/master/glommio/src/task/raw.rs#L347) in assertion [here](https://github.com/DataDog/glommio/blob/master/glommio/src/task/raw.rs#L295)

I'm using current master branch at ```cb1094189d03e911c77deaebe861ad3ab8ae57e6``` with rustc: ```rustc 1.55.0-nightly (e82b65026 2021-06-20)```

Test I'm using to reproduce an error https://github.com/LizardWizzard/parsley/blob/feature/initial-wal/core/src/wal/segment.rs#L475

Backtrace:
```
running 1 test
thread 'wal::segment::test::read_write_segment' panicked at 'assertion failed: `(left != right)`
  left: `0`,
 right: `0`', /home/dmitry/src/glommio/glommio/src/task/raw.rs:351:20
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/panicking.rs:92:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/panicking.rs:117:5
   4: glommio::task::raw::RawTask<F,R,S>::decrement_references
             at /home/dmitry/src/glommio/glommio/src/task/raw.rs:295:9
   5: glommio::task::raw::RawTask<F,R,S>::drop_task
             at /home/dmitry/src/glommio/glommio/src/task/raw.rs:351:20
   6: glommio::task::raw::RawTask<F,R,S>::run
             at /home/dmitry/src/glommio/glommio/src/task/raw.rs:497:17
   7: glommio::task::task_impl::Task::run
             at /home/dmitry/src/glommio/glommio/src/task/task_impl.rs:115:18
   8: glommio::executor::LocalExecutor::run_one_task_queue
             at /home/dmitry/src/glommio/glommio/src/executor/mod.rs:1074:25
   9: glommio::executor::LocalExecutor::run_task_queues
             at /home/dmitry/src/glommio/glommio/src/executor/mod.rs:1037:17
  10: glommio::executor::LocalExecutor::run::{{closure}}
             at /home/dmitry/src/glommio/glommio/src/executor/mod.rs:1164:27
  11: scoped_tls::ScopedKey<T>::set
             at /home/dmitry/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137:9
  12: glommio::executor::LocalExecutor::run
             at /home/dmitry/src/glommio/glommio/src/executor/mod.rs:1143:9
  13: core::wal::segment::test::read_write_segment
             at ./src/wal/segment.rs:478:9
  14: core::wal::segment::test::read_write_segment::{{closure}}
             at ./src/wal/segment.rs:475:5
  15: core::ops::function::FnOnce::call_once
             at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/ops/function.rs:227:5
  16: core::ops::function::FnOnce::call_once
             at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'wal::segment::test::read_write_segment' panicked at 'assertion failed: `(left != right)`
  left: `0`,
 right: `0`', /home/dmitry/src/glommio/glommio/src/task/raw.rs:351:20
stack backtrace:
   0:     0x55f285069350 - std::backtrace_rs::backtrace::libunwind::trace::hfa838fc631229987
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55f285069350 - std::backtrace_rs::backtrace::trace_unsynchronized::h93a23e36ec026219
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55f285069350 - std::sys_common::backtrace::_print_fmt::hba56c7f796a4152f
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55f285069350 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h214637f1e26310e1
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55f28508d19c - core::fmt::write::h7aa6cd0067dca82a
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/fmt/mod.rs:1110:17
   5:     0x55f285066095 - std::io::Write::write_fmt::heb07fc0616bbd06d
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/std/src/io/mod.rs:1640:15
   6:     0x55f28506b93b - std::sys_common::backtrace::_print::h2c2441c37e894fb5
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55f28506b93b - std::sys_common::backtrace::print::h4fb679ac439362ea
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55f28506b93b - std::panicking::default_hook::{{closure}}::h56bbadec2356e5d2
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/std/src/panicking.rs:208:50
   9:     0x55f28506b411 - std::panicking::default_hook::hb25822b45f6fdc4e
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/std/src/panicking.rs:225:9
  10:     0x55f28506c004 - std::panicking::rust_panic_with_hook::h4da5578e7277d2d4
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/std/src/panicking.rs:622:17
  11:     0x55f28506bae7 - std::panicking::begin_panic_handler::{{closure}}::h003783ddb3cba4e8
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/std/src/panicking.rs:519:13
  12:     0x55f28506982c - std::sys_common::backtrace::__rust_end_short_backtrace::hd138d2032731ed21
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55f28506ba49 - rust_begin_unwind
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/std/src/panicking.rs:515:5
  14:     0x55f284e22ba1 - core::panicking::panic_fmt::hbe99dddd3092ba3c
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/panicking.rs:92:14
  15:     0x55f28508bab8 - core::panicking::assert_failed_inner::h4fdb1013d187f202
  16:     0x55f284ff0afa - core::panicking::assert_failed::h44bf3100291815e3
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/panicking.rs:117:5
  17:     0x55f284e7dc93 - glommio::task::raw::RawTask<F,R,S>::decrement_references::ha735ffa7319dc6c7
                               at /home/dmitry/src/glommio/glommio/src/task/raw.rs:295:9
  18:     0x55f284e9309c - glommio::task::raw::RawTask<F,R,S>::drop_task::h5e5a6a279af25816
                               at /home/dmitry/src/glommio/glommio/src/task/raw.rs:351:20
  19:     0x55f284f913c2 - <glommio::task::task_impl::Task as core::ops::drop::Drop>::drop::h015ecd7dfe32f37b
                               at /home/dmitry/src/glommio/glommio/src/task/task_impl.rs:138:13
  20:     0x55f284f8b9ab - core::ptr::drop_in_place<glommio::task::task_impl::Task>::h8fe754e2829cc815
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/ptr/mod.rs:192:1
  21:     0x55f284f8c60f - core::ptr::drop_in_place<[glommio::task::task_impl::Task]>::hd46eae2bf3ea54ef
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/ptr/mod.rs:192:1
  22:     0x55f284f9031f - <alloc::collections::vec_deque::VecDeque<T> as core::ops::drop::Drop>::drop::hdc360fa69ffb4ad9
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/alloc/src/collections/vec_deque/mod.rs:135:13
  23:     0x55f284f8d6b7 - core::ptr::drop_in_place<alloc::collections::vec_deque::VecDeque<glommio::task::task_impl::Task>>::h1f2e84f01247f0ba
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/ptr/mod.rs:192:1
  24:     0x55f284f8a58b - core::ptr::drop_in_place<core::cell::UnsafeCell<alloc::collections::vec_deque::VecDeque<glommio::task::task_impl::Task>>>::ha8a5e67119df61f1
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/ptr/mod.rs:192:1
  25:     0x55f284f8a48f - core::ptr::drop_in_place<core::cell::RefCell<alloc::collections::vec_deque::VecDeque<glommio::task::task_impl::Task>>>::he6db19826e870cb4
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/ptr/mod.rs:192:1
  26:     0x55f284f8c6db - core::ptr::drop_in_place<glommio::executor::multitask::LocalQueue>::h9b79bc4e923b8139
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/ptr/mod.rs:192:1
  27:     0x55f284f8c7ab - core::ptr::drop_in_place<glommio::executor::multitask::LocalExecutor>::hd489bdeafaade895
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/ptr/mod.rs:192:1
  28:     0x55f284f8dc36 - <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop::h22d711c0cc74e700
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/alloc/src/rc.rs:1439:17
  29:     0x55f284f8d27b - core::ptr::drop_in_place<alloc::rc::Rc<glommio::executor::multitask::LocalExecutor>>::h0362f48f451bcab3
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/ptr/mod.rs:192:1
  30:     0x55f284f8b577 - core::ptr::drop_in_place<glommio::executor::TaskQueue>::hff7064ef2941e6cc
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/ptr/mod.rs:192:1
  31:     0x55f284f8cdfb - core::ptr::drop_in_place<core::cell::UnsafeCell<glommio::executor::TaskQueue>>::hb01b043f964cefc4
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/ptr/mod.rs:192:1
  32:     0x55f284f8cc5f - core::ptr::drop_in_place<core::cell::RefCell<glommio::executor::TaskQueue>>::h60e69de0d9b7fd14
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/ptr/mod.rs:192:1
  33:     0x55f284f8dd76 - <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop::h2a1ae6df2443e44b
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/alloc/src/rc.rs:1439:17
  34:     0x55f284f8d68b - core::ptr::drop_in_place<alloc::rc::Rc<core::cell::RefCell<glommio::executor::TaskQueue>>>::hb77eed961a88aa2f
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/ptr/mod.rs:192:1
  35:     0x55f284f8a4d3 - core::ptr::drop_in_place<core::option::Option<alloc::rc::Rc<core::cell::RefCell<glommio::executor::TaskQueue>>>>::h1a516687e5c96287
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/ptr/mod.rs:192:1
  36:     0x55f284f8bf4e - core::ptr::drop_in_place<glommio::executor::ExecutorQueues>::hc16c72e3a0135775
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/ptr/mod.rs:192:1
  37:     0x55f284f8d0bb - core::ptr::drop_in_place<core::cell::UnsafeCell<glommio::executor::ExecutorQueues>>::ha44ac7312e556af8
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/ptr/mod.rs:192:1
  38:     0x55f284f8cf0f - core::ptr::drop_in_place<core::cell::RefCell<glommio::executor::ExecutorQueues>>::h85328fb414f89dd5
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/ptr/mod.rs:192:1
  39:     0x55f284f8e1a6 - <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop::h44dbc92ab2302cae
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/alloc/src/rc.rs:1439:17
  40:     0x55f284f89deb - core::ptr::drop_in_place<alloc::rc::Rc<core::cell::RefCell<glommio::executor::ExecutorQueues>>>::hc0a261eef33e2eda
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/ptr/mod.rs:192:1
  41:     0x55f284f8ba67 - core::ptr::drop_in_place<glommio::executor::LocalExecutor>::ha4a111ef6e89286b
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/ptr/mod.rs:192:1
  42:     0x55f284eeeeed - core::wal::segment::test::read_write_segment::hfe10b8908a43af98
                               at /home/dmitry/src/parsley/core/src/wal/segment.rs:552:5
  43:     0x55f284e6293a - core::wal::segment::test::read_write_segment::{{closure}}::h24d25ed8f5391e7e
                               at /home/dmitry/src/parsley/core/src/wal/segment.rs:475:5
  44:     0x55f284e6572e - core::ops::function::FnOnce::call_once::h0b3c0e0fa7386ef8
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/ops/function.rs:227:5
  45:     0x55f284f193f3 - core::ops::function::FnOnce::call_once::h27530275e622330b
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/ops/function.rs:227:5
  46:     0x55f284f193f3 - test::__rust_begin_short_backtrace::h44c82cc7d0f4937d
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/test/src/lib.rs:577:5
  47:     0x55f284f17e8c - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h20c7d4b3f228af07
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/alloc/src/boxed.rs:1575:9
  48:     0x55f284f17e8c - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hbecd070b87bd6780
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/std/src/panic.rs:347:9
  49:     0x55f284f17e8c - std::panicking::try::do_call::h5b1333e8bd607b9c
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/std/src/panicking.rs:401:40
  50:     0x55f284f17e8c - std::panicking::try::h057fd2077bd509e5
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/std/src/panicking.rs:365:19
  51:     0x55f284f17e8c - std::panic::catch_unwind::h2f57d52ee610e8fc
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/std/src/panic.rs:434:14
  52:     0x55f284f17e8c - test::run_test_in_process::h9a32ca2677c7f812
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/test/src/lib.rs:600:18
  53:     0x55f284f17e8c - test::run_test::run_test_inner::{{closure}}::hb449ab58fec32d94
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/test/src/lib.rs:492:39
  54:     0x55f284ef1482 - test::run_test::run_test_inner::{{closure}}::h08d55d9698ad3c92
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/test/src/lib.rs:519:37
  55:     0x55f284ef1482 - std::sys_common::backtrace::__rust_begin_short_backtrace::h739a7c7a988c8471
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/std/src/sys_common/backtrace.rs:125:18
  56:     0x55f284ef5088 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::hff87f6709b4599d6
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/std/src/thread/mod.rs:481:17
  57:     0x55f284ef5088 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::heedb21d3eb169296
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/std/src/panic.rs:347:9
  58:     0x55f284ef5088 - std::panicking::try::do_call::h74a412fd6dfdff13
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/std/src/panicking.rs:401:40
  59:     0x55f284ef5088 - std::panicking::try::h90801934282c25f3
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/std/src/panicking.rs:365:19
  60:     0x55f284ef5088 - std::panic::catch_unwind::hee752c1088dd1104
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/std/src/panic.rs:434:14
  61:     0x55f284ef5088 - std::thread::Builder::spawn_unchecked::{{closure}}::h36779ab69c69bb28
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/std/src/thread/mod.rs:480:30
  62:     0x55f284ef5088 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h3dcc0d5454468332
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/core/src/ops/function.rs:227:5
  63:     0x55f285071a77 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hd1f9b751a68dd2ac
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/alloc/src/boxed.rs:1575:9
  64:     0x55f285071a77 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h22d732940e85619f
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/alloc/src/boxed.rs:1575:9
  65:     0x55f285071a77 - std::sys::unix::thread::Thread::new::thread_start::h04c7a9e17ed1032c
                               at /rustc/e82b65026dcadf0998e3abf9dabc677f63160de7/library/std/src/sys/unix/thread.rs:71:17
  66:     0x7f956b77a299 - <unknown>
  67:     0x7f956b555353 - <unknown>
  68:                0x0 - <unknown>
thread panicked while panicking. aborting.
```

Any tips on how to debug this kind of situation? E g how to detect which task is causing the issue. Maybe I'm using something incorrectly. Thanks in advance!

**Comment by artemyarulin** [comment]
I guess I had the same running this example https://github.com/DataDog/glommio/blob/master/examples/storage.rs using my machine in the past. 

Tested the same on some AWS VM and it went fine, realized that only difference is kernel version - upgraded that and issue went away. Just a guess

**Comment by glommer** [comment]
Hi

Sorry about that! Those are indeed the hardest parts of the executor. I can take a look at the reproducer later and see if I can reproduce, but I will take the time to explain what is going on, and hopefully it will make your debugging easier!

Tasks have an asynchronous lifetime. For example, when you do:
```
a = Task::local(...).detach()
```

you create a task, and that task is kept alive even after this context ends.

This is the same mechanism we use for `Waker`s, so if you, while implementing the `Future` trait, captures the `waker` present in the `Context`, the task needs to be kept alive.

This is done through a reference counting. This reference counting is atomic, because we allow wakers to exist in foreign executors because of channels and such. The actual act of waking is never atomic, but the reference count is.

Every time the reference count for a task is increased or decreased, there is an assert to make sure it is still sane.
The reason this exists is that if we were to overflow or underflow, debugging this -- which is already hard -- would become essentially impossible. With those asserts, at least you catch the underflow as soon as it happened.

What causes the reference count to *increase* ? cloning wakers, scheduling a task, etc.
What causes the reference count to *decrease* ? essentially the reverse, those things going out of scope.

In your case, the reference count decreased to -1 (underflow), so we assert right away (we compare the old value, which is 0)

When developing this, the way I would debug those issues was to essentially printing the address of the waker (so we can filter by address later), and every time the reference count goes up or down, try to figure out what is going on. If that doesn't lead us directly to the bug, it can at least help us in figuring out a simpler use case (instead of writing a file, just creating and cloning a task, for instance)

All occurrences to the reference count management should be under the `task` directory, and the vast majority of them under `raw.rs` (a couple of them are related to the join handle)

**Comment by glommer** [comment]
@artemyarulin do yuou have more details about the kernel versions you used? If there is a buggy io_uring in the kernel, then all bets are off. You can never rule out a random corruption in that case. But it could be just timing.

**Comment by LizardWizzard** [comment]
Thank you for the great explanation! Will try to debug this case. I had similar scenario in this code and panic disappeared when join handle was awaited instead of just dropped. But when I added more code error consistently appears independetly of that fact

**Comment by LizardWizzard** [comment]
Digged in a little. I'm using kernel version 5.12.11. Collected traces for two tasks. In my case second panic occurs in drop after the first one. So there are two tasks with rc underflow.

Trace for the first one:
```
0x7fef68002cb0 allocate header
0x7fef68002cb0 schedule
0x7fef68002cb0 clone waker
0x7fef68002cb0 increment header refs before: 1 refs after 2
Header { thread_id: 1, scheduled: true, running: false, completed: false, closed: false, handle: true, refcount: 2 }
0x7fef68002cb0 drop waker
0x7fef68002cb0 decrement header refs before: 2 refs after 1
Header { thread_id: 1, scheduled: true, running: false, completed: false, closed: false, handle: true, refcount: 1 }

0x7fef68002cb0 clone waker
0x7fef68002cb0 increment header refs before: 1 refs after 2
Header { thread_id: 1, scheduled: false, running: true, completed: false, closed: false, handle: true, refcount: 2 }
0x7fef68002cb0 drop task
0x7fef68002cb0 decrement header refs before: 2 refs after 1
Header { thread_id: 1, scheduled: false, running: false, completed: false, closed: false, handle: true, refcount: 1 }

0x7fef68002cb0 wake by ref
0x7fef68002cb0 drop waker
0x7fef68002cb0 decrement header refs before: 1 refs after 0
Header { thread_id: 1, scheduled: true, running: false, completed: false, closed: false, handle: true, refcount: 0 }

0x7fef68002cb0 drop future

0x7fef68002cb0 drop task
0x7fef68002cb0 decrement header refs before: 0 refs after -1
Header { thread_id: 1, scheduled: false, running: false, completed: true, closed: false, handle: true, refcount: -1 }
```
Trace for the second one:
```
0x7fef68003870 allocate header
0x7fef68003870 schedule
0x7fef68003870 clone waker
0x7fef68003870 increment header refs before: 1 refs after 2
Header { thread_id: 1, scheduled: true, running: false, completed: false, closed: false, handle: true, refcount: 2 }
0x7fef68003870 drop waker
0x7fef68003870 decrement header refs before: 2 refs after 1
Header { thread_id: 1, scheduled: true, running: false, completed: false, closed: false, handle: true, refcount: 1 }

0x7fef68003870 clone waker
0x7fef68003870 increment header refs before: 1 refs after 2
Header { thread_id: 1, scheduled: false, running: true, completed: false, closed: false, handle: true, refcount: 2 }
0x7fef68003870 drop task
0x7fef68003870 decrement header refs before: 2 refs after 1
Header { thread_id: 1, scheduled: false, running: false, completed: false, closed: false, handle: true, refcount: 1 }

0x7fef68003870 wake by ref
0x7fef68003870 drop waker
0x7fef68003870 decrement header refs before: 1 refs after 0
Header { thread_id: 1, scheduled: true, running: false, completed: false, closed: false, handle: true, refcount: 0 }

0x7fef68003870 drop future

0x7fef68003870 drop task
0x7fef68003870 decrement header refs before: 0 refs after -1
Header { thread_id: 1, scheduled: false, running: false, completed: false, closed: true, handle: true, refcount: -1 }
```
I'm continuing further investigation, just in case something comes to mind

**Comment by LizardWizzard** [comment]
Got interesting result, replaced ```waker.wake_by_ref()``` with ```waker.clone().wake()``` [here](https://github.com/LizardWizzard/parsley/blob/feature/initial-wal/core/src/wal/segment.rs#L353) and now test passes. So probably something in ```wake_by_ref``` behaves unexpectedly

**Comment by glommer** [comment]
Thanks!

Yeah, this makes sense because `clone` will bump the reference count. Here's another pointer:
Usually when you are just acquiring a reference, we don't mess with the reference count (the same way that a reference to an `Rc` does not increase its reference count).

But there are situations in which we do. See for instance this code inside `schedule`:

```
        // Calling of schedule functions itself does not increment references,
        // if the schedule function has captured variables, increment references
        // so if task being dropped inside schedule function , function itself
        // will keep valid data till the end of execution.
        if mem::size_of::<S>() > 0 {
            guard = Some(Waker::from_raw(Self::clone_waker(ptr)));
        } else {
            guard = None;
        }
 ```

Essentially what is happening there is that the task itself, by virtue of being scheduled, doesn't require reference count to be manipulated. But the schedule function, which can capture references to other things, imposes that requirement.

There are maybe then other places in which we should be doing this and are not.

**Comment by LizardWizzard** [comment]
Have some observations. Saw this comment 
```
// Schedule the task. There is no need to call `Self::schedule(ptr)`
// because the schedule function cannot be destroyed while the waker is
// still alive.
```
and in the trace I see that waker is dropped after the call to `wake_by_ref` and refcount reaches zero. Also if I actually call `schedule` test errors with panic in the same place and a message: `free(): double free detected in tcache 2`

Will dig deeper, I think I have only partial understanding on whats going on, will try to connect pieces together.

Also, is it correct to have a header with handle bit set (does it mean that join handle is alive?) and refcount equal to zero? Saw that case in trace attached above.

By the way, if I insert increment_references call [here](https://github.com/DataDog/glommio/blob/master/glommio/src/task/raw.rs#L271) it works correctly and by traces there are no tasks left dangling, so for all tasks there is a decrement with resulting refcount 0. But I'm not sure is it correct for all possible cases

**Comment by LizardWizzard** [comment]
I might have found the cause (or just become closer to it). Also created a much shorter reproducer. Here it is:
```rust
use std::task::{Poll, Waker};
use std::{cell::RefCell, rc::Rc};

use futures::future::join_all;
use futures::future::poll_fn;
use glommio::prelude::*;

enum TaskState {
    Pending(Option<Waker>),
    Ready,
}

fn main() -> () {
    let producer = LocalExecutorBuilder::default()
        .spawn(move || async move {
            let slot: Rc<RefCell<TaskState>> = Rc::new(RefCell::new(TaskState::Pending(None)));
            let cloned_slot = slot.clone();
            let jh = Local::local(async move {
                // first task, places waker of self into slot, when polled checks for result, if it's ready, returns Ready,
                // otherwise return Pending
                poll_fn::<(), _>(|cx| {
                    let current = &mut *cloned_slot.borrow_mut();
                    match current {
                        TaskState::Pending(maybe_waker) => match maybe_waker {
                            Some(_) => unreachable!(),
                            None => {
                                *current = TaskState::Pending(Some(cx.waker().clone()));
                                Poll::Pending
                            },
                        },
                        TaskState::Ready => Poll::Ready(())
                    }
                }).await;
            }).detach();
            let jh2 = Local::local(async move {
                    // second task, checks slot for first task waker, wakes it by ref, and then it is dropped.
                    let current = &mut *slot.borrow_mut();
                    match current {
                        TaskState::Pending(maybe_waker) => {
                            let waker = maybe_waker.take().unwrap();
                            waker.wake_by_ref();
                            println!("dbg waker {:?}", waker);
                            *current = TaskState::Ready;  // <-- waker dropped here, refcount is zero
                        },
                        TaskState::Ready => unreachable!(), // task cannot be ready at this time
                    }
            }).detach();
            let r = join_all(vec![jh, jh2]).await;
        })
        .unwrap();
   
    producer.join().unwrap();
}
```
In this code waker is dropped right after the call to `wake_by_ref`. Also if I replace `wake_by_ref` by just `wake` it will work fine, so there is no `waker.clone()` involved to bump refcount.

I'm not sure how to handle the issue. One idea is to detect this situation in drop_waker. E. g. when refcount is 1 but handle is active do not decrement references. So this can be done via
```rust
if (refs == 0) && state & HANDLE != 0 {
    // waker is dropped, but handle is still active
    // this can be caused by a dropping of waker after a call to wake_by_ref
    Self::increment_references(&mut *(raw.header as *mut Header));
}
```
somewhere [here](https://github.com/DataDog/glommio/blob/master/glommio/src/task/raw.rs#L323). I'm not sure about correctness of this solution, but I checked that no existing tests fail with this addition.

**Comment by glommer** [comment]
Thanks Dmitry! The reproducer helps a lot. I have a hunch that this has to do with the schedule function that we use. I'll try to take a look at this tonight

**Comment by glommer** [comment]
I don't think this proposed solution will work. The fact that the join handle is still alive is a fortunate coincidence of the way you coded the reproducer:

if you don't capture them in their `jh` variables, but instead add a `glommio::timer::sleep` after both `detach()`, then this still crashes because they are killed right away.

**Comment by glommer** [comment]
The issue here seems to be a potential double-schedule issue.

I have uploaded an attempted fix here: https://github.com/glommer/glommio/pull/new/attempted-fix

Please test.

I am not proposing this a fix just yet, because it doesn't make sense to me that drop_waker() is even called in the `wake_by_ref` case, so I am investigating why this is the case

**Comment by glommer** [comment]
I think what happens is that when you call `wake`, that is a consuming call, so `drop_waker` never gets called by the environment. When you call `wake_by_ref`, the waker is not consumed. So eventually it does when the block goes out of scope and now we have two schedules:

- the call from `wake_by_ref` itself,
- the implicit call that happens when `wake` is dropped.

We still need to increase the reference count as we are closing, but we should not schedule twice.

The schedule function is this:

```
        let schedule = move |runnable: Runnable| {
            let tq = tq.upgrade();

            if let Some(tq) = tq {
                {
                    let queue = tq.borrow();
                    queue.ex.local_queue.push(runnable);
                }
                maybe_activate(tq);
            }
        };
 ```

So as you can see, it just pushes something to the back of a queue. As a result, the task ends up running once after it is already closed.

**Comment by LizardWizzard** [comment]
Thank you for looking at this. Proposed solution sounds reasonable, but reproducer still crashes in the same place. Probably it works for case with sleep instead of keeping join handles. So the condition added to `drop_waker`: `if state & SCHEDULED == 0` is not matching because of  `state & HANDLE == 0` requirement above, so in case of unmodified reproducer join handles are still alive. Also I don't see double schedule in traces for that task.

I've added both scenarios (with sleep and with join handles) as tests [here](https://github.com/LizardWizzard/glommio/commit/ebe2d7bb255aa23d53d1abe1f9d7408b958d3a63). The case without join handles is working correctly now, but one with join handles fail.

You are absolutely right about the consequences of `drop_waker` call after `wake_by_ref`. `wake_by_ref` doesn`t consume waker, but waker can be dropped straight away.

Can we detect this case by checking for `(refs == 0) && state & SCHEDULED != 0` instead of check for alive join handle? Will it make more sense? I think it might be, because scheduling a task with zero references doesn`t make sense. May be this is another ad-hoc solution and the fundamental one lies somewhere deeper. Proposed solution at the end of the drop_waker:
```rust
} else if (refs == 0) && state & SCHEDULED != 0 {
    Self::increment_references(&mut *(raw.header as *mut Header));
}
```

**Comment by glommer** [comment]
All those solutions look reasonable, but as you could see, including mine, the problem is the corner cases =)

Let me take a deep look at this again today and I will get back on that.

Thanks!

**Comment by glommer** [comment]
I will post a PR with a fix now. I am pretty confident in the fix, because this finally makes sense. But I'd appreciate some testing before it goes in.

Also, I'd very much like to have the tests you wrote merged too. Because you wrote them, I am not including them in the PR. My preference is that you send them to preserve authorship, but if you prefer I'm happy to merge them too.

I'd like to have 4 tests, though: 2 with wake, 2 with `wake_by_ref`.

**Comment by LizardWizzard** [comment]
Looks great! Tests pass. Thank you! I've submitted tests as a PR to your branch so they can be merged at once with the fix so there is no failing tests in master. Let me know if there is a better option

**Comment by glommer** [comment]
I think it's best to send it separately. I didn't see your patch in the PR now that I merged. Not sure if there is anything I should do in the github interface for that to appear.
