### ISSUE TITLE
dma_file_stream already borrowed BorrowMutError on close

### ISSUE THREAD

**Issue by artemyarulin** [DataDog/glommio#465]
Using v.0.6.0 when my app is under heavy load it sometimes chashes with error
```
thread 'unnamed-7' panicked at 'already borrowed: BorrowMutError', /home/fessguid/Projects/glommio/glommio/src/io/dma_file_stream.rs:1436:36
stack backtrace:
   0: rust_begin_unwind
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:101:14
   2: core::result::unwrap_failed
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/result.rs:1617:5
   3: core::result::Result<T,E>::expect
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/result.rs:1259:23
   4: core::cell::RefCell<T>::borrow_mut
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/cell.rs:940:9
   5: <glommio::io::dma_file_stream::DmaStreamWriter as futures_io::if_std::AsyncWrite>::poll_close
             at /home/fessguid/Projects/glommio/glommio/src/io/dma_file_stream.rs:1436:25
   6: <futures_util::io::close::Close<W> as core::future::future::Future>::poll
             at /home/fessguid/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.17/src/io/close.rs:26:9
   7: crawler::storage::Storage::close::{{closure}}
             at ./src/storage.rs:128:9
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/future/mod.rs:80:19
   9: crawler::start::{{closure}}::{{closure}}::{{closure}}
             at ./src/lib.rs:122:33
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/future/mod.rs:80:19
  11: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/future/future.rs:119:9
  12: glommio::task::raw::RawTask<F,R,S>::run
             at /home/fessguid/Projects/glommio/glommio/src/task/raw.rs:459:20
  13: glommio::task::task_impl::Task::run
             at /home/fessguid/Projects/glommio/glommio/src/task/task_impl.rs:124:22
  14: glommio::executor::LocalExecutor::run_one_task_queue
             at /home/fessguid/Projects/glommio/glommio/src/executor/mod.rs:1065:25
  15: glommio::executor::LocalExecutor::run_task_queues
             at /home/fessguid/Projects/glommio/glommio/src/executor/mod.rs:1028:17
  16: glommio::executor::LocalExecutor::run::{{closure}}
             at /home/fessguid/Projects/glommio/glommio/src/executor/mod.rs:1158:27
  17: scoped_tls::ScopedKey<T>::set
             at /home/fessguid/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137:9
  18: glommio::executor::LocalExecutor::run
             at /home/fessguid/Projects/glommio/glommio/src/executor/mod.rs:1134:9
  19: glommio::executor::LocalExecutorBuilder::spawn::{{closure}}
             at /home/fessguid/Projects/glommio/glommio/src/executor/mod.rs:565:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'unnamed-7' panicked at 'already borrowed: BorrowMutError', /home/fessguid/Projects/glommio/glommio/src/io/dma_file_stream.rs:1051:36
stack backtrace:
   0:     0x556153ccbacc - std::backtrace_rs::backtrace::libunwind::trace::h3fea1eb2e0ba2ac9
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x556153ccbacc - std::backtrace_rs::backtrace::trace_unsynchronized::h849d83492cbc0d59
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x556153ccbacc - std::sys_common::backtrace::_print_fmt::he3179d37290f23d3
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x556153ccbacc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h140f6925cad14324
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x556153cedf7c - core::fmt::write::h31b9cd1bedd7ea38
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/fmt/mod.rs:1150:17
   5:     0x556153cc6845 - std::io::Write::write_fmt::h1fdf66f83f70913e
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/io/mod.rs:1667:15
   6:     0x556153ccd6e0 - std::sys_common::backtrace::_print::he7ac492cd19c3189
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x556153ccd6e0 - std::sys_common::backtrace::print::hba20f8920229d8e8
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x556153ccd6e0 - std::panicking::default_hook::{{closure}}::h714d63979ae18678
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:210:50
   9:     0x556153ccd297 - std::panicking::default_hook::hf1afb64e69563ca8
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:227:9
  10:     0x556153ccdd94 - std::panicking::rust_panic_with_hook::h02231a501e274a13
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:624:17
  11:     0x556153ccd870 - std::panicking::begin_panic_handler::{{closure}}::h5b5e738edf361af7
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:521:13
  12:     0x556153ccbf94 - std::sys_common::backtrace::__rust_end_short_backtrace::h601a115def7987b1
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x556153ccd7d9 - rust_begin_unwind
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
  14:     0x556153a53481 - core::panicking::panic_fmt::h7a58c8fffc5559a4
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:101:14
  15:     0x556153a53573 - core::result::unwrap_failed::h1036b5c6eb8030dd
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/result.rs:1617:5
  16:     0x556153c824b5 - core::result::Result<T,E>::expect::h7f691b6049c70494
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/result.rs:1259:23
  17:     0x556153c824b5 - core::cell::RefCell<T>::borrow_mut::h4a84e7a1f2165603
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/cell.rs:940:9
  18:     0x556153c824b5 - <glommio::io::dma_file_stream::DmaStreamWriter as core::ops::drop::Drop>::drop::hfa5474316dc05f6c
                               at /home/fessguid/Projects/glommio/glommio/src/io/dma_file_stream.rs:1051:25
  19:     0x556153a60475 - core::ptr::drop_in_place<glommio::io::dma_file_stream::DmaStreamWriter>::hd880d8fd7979be30
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ptr/mod.rs:188:1
  20:     0x556153a60475 - core::ptr::drop_in_place<crawler::storage::Storage>::h91f9f39abd1f0f8b
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ptr/mod.rs:188:1
  21:     0x556153a702c2 - crawler::start::{{closure}}::{{closure}}::{{closure}}::hb1a35150d5d86eba
                               at /home/fessguid/Projects/kapteko/services/crawler/src/lib.rs:123:29
  22:     0x556153a702c2 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h893f32f03088b0ef
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/future/mod.rs:80:19
  23:     0x556153aa5302 - <core::pin::Pin<P> as core::future::future::Future>::poll::h2e5aec3e56fc1c61
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/future/future.rs:119:9
  24:     0x556153aa5302 - glommio::task::raw::RawTask<F,R,S>::run::h03467a9c04647368
                               at /home/fessguid/Projects/glommio/glommio/src/task/raw.rs:459:20
  25:     0x556153c78ea1 - glommio::task::task_impl::Task::run::h04c837a1934e39f0
                               at /home/fessguid/Projects/glommio/glommio/src/task/task_impl.rs:124:22
  26:     0x556153c78ea1 - glommio::executor::LocalExecutor::run_one_task_queue::h53f4ddab8a208858
                               at /home/fessguid/Projects/glommio/glommio/src/executor/mod.rs:1065:25
  27:     0x556153c78ea1 - glommio::executor::LocalExecutor::run_task_queues::ha402489c2da7af95
                               at /home/fessguid/Projects/glommio/glommio/src/executor/mod.rs:1028:17
  28:     0x556153a97a9e - glommio::executor::LocalExecutor::run::{{closure}}::h0c2aad4ffe6af4e0
                               at /home/fessguid/Projects/glommio/glommio/src/executor/mod.rs:1158:27
  29:     0x556153a97a9e - scoped_tls::ScopedKey<T>::set::h2b62256f68e0b6c4
                               at /home/fessguid/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137:9
  30:     0x556153ab3893 - glommio::executor::LocalExecutor::run::h66cdba426caa657d
                               at /home/fessguid/Projects/glommio/glommio/src/executor/mod.rs:1134:9
  31:     0x556153a9836b - glommio::executor::LocalExecutorBuilder::spawn::{{closure}}::h821a20bbe980e1d4
                               at /home/fessguid/Projects/glommio/glommio/src/executor/mod.rs:565:17
  32:     0x556153a9836b - std::sys_common::backtrace::__rust_begin_short_backtrace::hf1339b952a6dd4ea
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:125:18
thread 'unnamed-1' panicked at 'already borrowed: BorrowMutError', /home/fessguid/Projects/glommio/glommio/src/io/dma_file_stream.rs:1436:36
  33:     0x556153a81195 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::h8b32c40d7f75844f
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/thread/mod.rs:481:17
  34:     0x556153a81195 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h711b2cabf724ab08
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panic/unwind_safe.rs:271:9
  35:     0x556153a81195 - std::panicking::try::do_call::hb1e9be443376a7e7
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:403:40
  36:     0x556153a81195 - std::panicking::try::h668a73dcfb016d3c
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:367:19
  37:     0x556153a81195 - std::panic::catch_unwind::h643ddb6aeb836ee3
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panic.rs:129:14
  38:     0x556153a81195 - std::thread::Builder::spawn_unchecked::{{closure}}::hf759678414726c9d
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/thread/mod.rs:480:30
  39:     0x556153a81195 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h08fb558bbfca7842
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:227:5
  40:     0x556153cd1ce3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hf2a5e508372e2387
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/alloc/src/boxed.rs:1636:9
  41:     0x556153cd1ce3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h46642f5b75478456
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/alloc/src/boxed.rs:1636:9
  42:     0x556153cd1ce3 - std::sys::unix::thread::Thread::new::thread_start::h1fbdb50adbde1cab
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys/unix/thread.rs:106:17
thread 'unnamed-5' panicked at 'already borrowed: BorrowMutError', /home/fessguid/Projects/glommio/glommio/src/io/dma_file_stream.rs:1436:36
  43:     0x7f0ddde9a609 - start_thread
                               at /build/glibc-eX1tMB/glibc-2.31/nptl/pthread_create.c:477:8
  44:     0x7f0dddc6c293 - clone
  45:                0x0 - <unknown>

```
basically I create X executers, in each of them I create N workers where each worker has it's own `DmaStreamWriter`. Now and then workers write to it and once done call `writer.close().await.unwrap()` which sometimes fail with the following error.

After running some `git bisect` I've found that I can reproduce this error right after https://github.com/DataDog/glommio/commit/da1ed020e145fa64e7a8dca0dfb022d7a9d93e7c 

Adding logs I've seen state borrowed in https://github.com/DataDog/glommio/blob/aeef079250822920b4e31077e7895b735679d0b0/glommio/src/io/dma_file_stream.rs#L1051 and then at  https://github.com/DataDog/glommio/blob/aeef079250822920b4e31077e7895b735679d0b0/glommio/src/io/dma_file_stream.rs#L1436 
sometimes it crashes with borrow in that line https://github.com/DataDog/glommio/blob/aeef079250822920b4e31077e7895b735679d0b0/glommio/src/io/dma_file_stream.rs#L947

Unfortunately I cannot create a small to reproduce example as it happens only under heavy load. Although I can reproduce it almost every time on local env, so feel free to ask if you need additional info.

**Comment by glommer** [comment]
Thanks @artemyarulin . Adding @shikhar who wrote the original commit.

I will be able to take a look at it myself in a couple of days as well

**Comment by shikhar** [comment]
Thanks @glommer and sorry about the bug @artemyarulin. I will try to take a look soon!

**Comment by glommer** [comment]
This code is fishy, and I think I may have fixed it by accident (while fixing something else) after 0.6.0

@artemyarulin would you be able to try and reproduce this with our current master branch ?

**Comment by artemyarulin** [comment]
Yep, with master everything works - thanks

**Comment by glommer** [comment]
I will reopen because I want to release 0.6.1 with this fix. The next version will change the API considerably in some areas.
